#######################################################################################
# Book settings
title : Programming for Quantitative Economics
author: Thomas J. Sargent and John Stachurski
logo: 'qe-logo-large.png'

# Information about where the book exists on the web
description: >-
  This book presents a set of lectures on Python programming for quantitative economics, designed and written by **Thomas J. Sargent** and **John Stachurski**.

exclude_patterns: ["lab/*"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off

#######################################################################################
# HTML-specific settings
html:
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar

#######################################################################################
# Launch button settings
repository:
    url: https://github.com/2i2c-org/utoronto-demo


launch_buttons:
    binderhub_url             : "https://mybinder.org"
    jupyterhub_url            : "https://utoronto.2i2c.cloud"
    notebook_inferface        : "jupyterlab"


sphinx:
    extra_extensions: ["sphinx_panels"]
 